# Generated by Django 4.0 on 2022-06-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_id', models.BooleanField(default=False, verbose_name='Verified user')),
                ('avatar', models.ImageField(blank=True, default='static/img/default_profile.jpg', null=True, upload_to='profile/%Y/%m/%d', verbose_name='Avatar')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('status', models.CharField(choices=[('bgn', 'beginner'), ('adv', 'advanced'), ('ext', 'expert')], default='bgn', max_length=3, verbose_name='Loyalty status')),
                ('user', models.OneToOneField(error_messages={'invalid': 'Please enter a valid value', 'required': 'This field is required'}, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'app_profile',
                'ordering': ['user'],
            },
        ),
    ]
